// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { StorageContract$Type } from "./StorageContract";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["StorageContract"]: StorageContract$Type;
    ["contracts/contract.sol:StorageContract"]: StorageContract$Type;
  }

  interface ContractTypesMap {
    ["StorageContract"]: GetContractReturnType<StorageContract$Type["abi"]>;
    ["contracts/contract.sol:StorageContract"]: GetContractReturnType<StorageContract$Type["abi"]>;
  }
}
